### PR TITLE
Changes generator to not use reflection for host functions

### PR DESCRIPTION
**Pull request by codefromthecrypt**
*Description of changes:*

This changes the generator to avoid performance penalty in host calls due to reflection.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
@knqyf263 ok after this, let's cut a version and I can help folks move to it!

**Comment by codefromthecrypt** [comment]
@knqyf263 friendly nag :D I've found a few projects using your plugin and I'd love to help bump them, but might as well give a perf boost for their trouble. wdyt?

**Comment by knqyf263** [comment]
Thanks for your contribution. I'm currently on a long vacation on a cruise ship and cannot test this PR. I've invited you to this project so you can merge the PR and cut a new release.

**Comment by codefromthecrypt** [comment]
@knqyf263 your explanation made my day 🛳️ !

**Comment by codefromthecrypt** [comment]
first victim https://github.com/deislabs/dapr-wasm-exp/pull/6

**Comment by codefromthecrypt** [comment]
https://github.com/aramase/hello-wasm/pull/1

**Pull request merged**
